### ISSUE TITLE
Proofread chapters/conclusions

### ISSUE THREAD

**Issue by tungufoss** [ALICE-InRu/Thesis#13]
### [Source](https://github.com/ALICE-InRu/Thesis/blob/master/chapters/conclusions.tex)

Needs to fully encapsulate the entire thesis. Preferably it should be comprehensible to be read on its own.

**Comment by bnvk** [comment]
The second sentence of...

```
The nature of CMA-ES is to explore suboptimal routes until it converges to an 
optimal route. So perhaps, if \PhiSet{\CMAES} wasn't based on following the 
CMA-ES trajectory, but rather using the actual features encountered during its 
optimisation. 
```

...hangs in a weird way and feels there is a second part to the thought, something like 

```
but rather using the actual features encountered during its 
optimisation would find optimal route faster
```

But, i'm unsure the meaning of these terms.

**Comment by tungufoss** [comment]
Thank you @bnvk
